### ISSUE TITLE
Add ability to not attach any artifacts.

### ISSUE THREAD

**Issue by jhdgithub** [simpligility/android-ndk-maven-plugin#13]
Currently .har and .so are attached as artifacts.  .har can be disabled (attachHeaderFiles) but not .so-files.
Please add a configuration to not attach them also.  When uploading to a public repository we don't wan't  to duplicate files.  The .so-files are in the apk already, when this plugin is part of a complete Android project that produces an apk.

Thanks

**Comment by johanlindquist** [comment]
@jhdgithub - assume you have the android-maven-plugin "looking for" artifacts in the target folder and using that?  That would work and we can probably add support for that.  If you are running the build in separate sub-modules it cant be done unfortunately - the APK plugin will have to look for attached artifacts in the reactor.

**Comment by johanlindquist** [comment]
To clarify, the module you are building the APK in also contains the NDK plugin to compile a native library?  If its a pure native library project, the flag will be disallowed since there needs to be at least one artifact attached to a module.

**Comment by jhdgithub** [comment]
Yes, I use android-maven-plugin for the apk, and android-ndk-maven-plugin just builds the ndk stuff in the same module.

**Comment by johanlindquist** [comment]
Committed to master - please give it a spin and let me know.  Note that using the flag on a "pure" native project will break the build

**Comment by jhdgithub** [comment]
Works OK with attachLibrariesArtifacts false.

**Comment by johanlindquist** [comment]
Ok, will be in the next release
