### ISSUE TITLE
Handle new file structures used in NDK r11

### ISSUE THREAD

**Issue by johanlindquist** [simpligility/android-ndk-maven-plugin#18]
Currently, the build is failing due to the plugin being unable to find RELEASES.txt in the root folder of the NDK.  Seems this file was replaced with source.properties

**Comment by johanlindquist** [comment]
Hi @mosabua - any chance of cutting another minor release for this issue?  The CI tests are now passing (using r11c)

Thanks,

Johan

**Comment by mosabua** [comment]
Sure.... I just did a android-maven-plugin one... so if this is ready,.. I can cut it tonight.. wdyt?

**Comment by johanlindquist** [comment]
If you could, that'd be great - tests have passed on both 10d and 11c so it
should all be good.

Johan
