### ISSUE TITLE
Consistency for properties

### ISSUE THREAD

**Issue by mosabua** [simpligility/android-ndk-maven-plugin#5]
I believe all configuration properties should be consistent. 

E.g. the property in the ndk maven plugin configuration should have some sort of name that is meaningful like toolChain and the user property should then be android.ndk.toolChain

This should be consistent in the sense that all user properties use android.ndk.propertyName..

**Comment by johanlindquist** [comment]
Sure, makes sense to me - if you give it stab, i'll take a look and we are bound to come to a consensus. :)

**Comment by johanlindquist** [comment]
Please see commits - updated to all use android.ndk.propertyName.  Something along those lines?

Beware of the botched the commit message (facepalm)

**Comment by mosabua** [comment]
That looks good. Imho we can merge that branch to master. We just have to update the examples as well. I will port the usage of the takari testing stuff from the android maven plugin in the next days.

**Comment by johanlindquist** [comment]
But the examples don't use properties do they?

**Comment by mosabua** [comment]
Not that I am aware of. But worth checking just in case we also changed parameter names..

**Comment by johanlindquist** [comment]
Ok, so maybe I am naive but to supply properties, that would be done on the command line or?  All configuration for the examples are done as part of the pom so I see no issue here.

**Comment by johanlindquist** [comment]
@mosabua Trying to get back on track with this - any thoughts as to what else is needed to close this?

**Comment by mosabua** [comment]
It might be all done.... can you check through the codebase?

**Comment by mosabua** [comment]
This looks good. Anything we find later can be a bug fix.
