### ISSUE TITLE
Site setup

### ISSUE THREAD

**Issue by mosabua** [simpligility/android-ndk-maven-plugin#7]
We should port enough of a shell for the site rendering from the android maven plugin to be able to push a site with some docs live. 

Lots of things can just be links to the android maven plugin site.

**Comment by mosabua** [comment]
But some are obviously different. E.g. the examples page content..

**Comment by johanlindquist** [comment]
@mosabua What is needed for this?  Assume you mean we should be able to use the site plugin etc?

**Comment by mosabua** [comment]
We should take the asciidoc and site plugin related stuff from the main plugin and put it in here, mainly stuff from the pom and src/site and change the navigation in site.xml to mostly link to the main plugin for stuff like contributing and so on.

**Comment by johanlindquist** [comment]
Ok, can take a look - do we have a staging where i can share this for
testing?

**Comment by mosabua** [comment]
Just build it locally and throw it into a pull request and merge it when you are happy. I can check it locally as well. Just busy with migrating a google code project but then I will look at the android plugins again @simpligility/android-maven-plugins-core-committers  fyi...

**Comment by mosabua** [comment]
Once we are semi happy we can cut another release that publishes the site..

**Comment by mosabua** [comment]
If we want to publish the site separately from the release we can use the same setup with a different profile.. see https://github.com/simpligility/ksoap2-android

**Comment by mosabua** [comment]
Done it all now.
